
[manager]
# NOTE: can combined with tmTheme (sublime colorshceme file) for preview code highlight
# highlight = "path/to/tmTheme"

cwd = { fg = "#a9b1d6", italic = true }

# Hovered
hovered         = { bg = "#292e42" }
preview_hovered = { bg = "#292e42" }

# Find
find_keyword  = { fg = "#1f2335", bg = "#ff9e64", bold = true }
find_position = { fg = "#0db9d7", bg = "#22374b", bold = true }

# Marker
marker_copied   = { fg = "#73daca", bg = "#73daca" }
marker_cut      = { fg = "#f7768e", bg = "#f7768e" }
marker_marked   = { fg = "#bb9af7", bg = "#bb9af7" }
marker_selected = { fg = "#7aa2f7", bg = "#7aa2f7" }

# Tab
tab_active   = { fg = "#c0caf5", bg = "#292e42" }
tab_inactive = { fg = "#3b4261", bg = "#24283b" }
tab_width    = 1

# Count
count_copied   = { fg = "#c0caf5", bg = "#41a6b5" }
count_cut      = { fg = "#c0caf5", bg = "#db4b4b" }
count_selected = { fg = "#c0caf5", bg = "#3d59a1" }
# Border
border_symbol = "│"
border_style  = { fg = "#29a4bd" }

[status]
separator_open  = ""
separator_close = ""
separator_style = { fg = "#3b4261", bg = "#3b4261" }

# Mode
mode_normal = { fg = "#1f2335", bg = "#7aa2f7", bold = true }
mode_select = { fg = "#1f2335", bg = "#bb9af7", bold = true }
mode_unset  = { fg = "#1f2335", bg = "#9d7cd8", bold = true }

# Progress
progress_label  = { fg = "#a9b1d6", bold = true }
progress_normal = { fg = "#24283b" }
progress_error  = { fg = "#f7768e" }

# Permissions
permissions_t = { fg = "#7aa2f7" }
