return {
  {
    "nvim-treesitter/nvim-treesitter",
    dependencies = { "OXY2DEV/markview.nvim" },
    lazy = false,
    opts = {
      ensure_installed = {
        "angular",
        "kotlin",
        "html",
        "javascript",
        "jsdoc",
        "json",
        "jsonc",
        "lua",
        "luadoc",
        "luap",
        "markdown",
        "markdown_inline",
        "norg",
        "tsx",
        "typescript",
        "python",
        "yaml",
        "scss",
        "vim",
        "vimdoc",
        "http",
      },
    },
  },
}
